Add style assets
BritneyS/SparkleSpin pull request #1
Opened 2019-02-20 20:39 UTC by BritneyS

## What you did :question:
For this PR, I added the style assets for the project: Fonts, App Icons, Colors, and Favicons (Home, Delete, and Exit).

## How to test it :microscope:
Run the app to see the added Fonts, as well as asset folders 'Assets', 'Colors' and 'Icons'.

## Any background context you want to provide? :question:
Checking Apple's guidelines, an 'Exit' or 'Quit' button might not be necessary. If there's no need for it in the design, I will remove the 'Exit' favicon.

The 'Delete' favicon may also be changed.

## Screenshots (if applicable) :camera:
![screen shot 2019-02-20 at 2 57 50 pm](https://user-images.githubusercontent.com/8409475/53122356-6e788e00-3524-11e9-8920-50476b854b28.png)
![screen shot 2019-02-20 at 2 58 12 pm](https://user-images.githubusercontent.com/8409475/53122367-733d4200-3524-11e9-8cda-30d530a8e8a4.png)
![screen shot 2019-02-20 at 2 58 51 pm](https://user-images.githubusercontent.com/8409475/53122370-77695f80-3524-11e9-8e39-af86380c1006.png)
![screen shot 2019-02-20 at 2 58 58 pm](https://user-images.githubusercontent.com/8409475/53122381-7e906d80-3524-11e9-808c-33c87c0bf345.png)
![screen shot 2019-02-20 at 3 34 38 pm](https://user-images.githubusercontent.com/8409475/53122647-14c49380-3525-11e9-9d26-c8ee9311e480.png)

2019-02-21 19:53 UTC, tolkiana commented
Looks like there's a reference to the font files, but there are not fonts in the folder. This is how it looks for me:
<img width="271" alt="screen shot 2019-02-21 at 1 51 36 pm" src="https://user-images.githubusercontent.com/5129887/53197434-d4761b80-35df-11e9-92d7-849575cdfd48.png">

2019-02-21 19:56 UTC, tolkiana commented on SparkleSpin/Style/Font.swift
> +}
I really like this folder (`/style`) and all the content there. These files look very well organized and they will come handy once you start using all this. 🙌

2019-02-21 19:56 UTC, tolkiana requested changes
Everything looks great, the only missing thing are the fonts.

2019-02-22 15:14 UTC, BritneyS commented
> Everything looks great, the only missing thing are the fonts.

XCode directory didn't match disk directory, and font files themselves weren't tracked. Should be fine now!

2019-02-22 16:33 UTC, tolkiana approved these changes
Looks good now! 🌮

2019-02-22 18:01 UTC, merged